### ISSUE TITLE
pypi

### ISSUE THREAD

**Issue by llllllllll** [thomasballinger/lazyload#3]
Can you put this up on pypi; I would like to use it in another project.

**Comment by thomasballinger** [comment]
edit: Yep, I like this project and will release it if you want me to. (self-deprecating comments removed)

**Comment by thomasballinger** [comment]
@llllllllll Would you be interested in being the maintainer instead? My goals for this project are
1. for it to declare that some modules/packages should be loaded lazily in the future, so it can be used as wrapper code without having to modify either the code doing the importing or the library being imported.
2. for it to keep Python 2.7 support

If you're on board with those, I'd just as soon have someone actually using the project for more than a hack (like I am) maintaining it. If you'd rather not take this on, I'll release it on PyPI anyway.

**Comment by thomasballinger** [comment]
just in case you're not already aware, as a temp workaround this works:

```
pip install git+git://github.com/thomasballinger/lazyload.git
```

**Comment by llllllllll** [comment]
I don't know if I would like to be the maintainer because I think I would like to build a simmilar but different feature into my lazy library. One limitation of this is that if I have:

``` python
from module import attribute
```

then `module` will be strictly loaded to give me `attribute`; however, I would like it to return a `thunk` that depends on an import of `module`. The only reason that I would feel bad about puting that into this package is that I am not building my lazy package with production code in mind.

**Comment by thomasballinger** [comment]
Alright, I'm going to publish this. Last chance to claim "lazyload" as a name ;)

**Comment by llllllllll** [comment]
All yours ^^

**Comment by thomasballinger** [comment]
Done
